# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [5]:
list=[1,2,3,4,5]
array = np.array(list)
print(array)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [7]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
array=np.array(matrix)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [9]:
matrix=np.arange(1,18,2)
matrix1=matrix.reshape(3,3)
print(matrix1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [13]:
arr=np.random.randint(0,10,10)
print(arr)

[7 4 2 3 4 0 2 6 1 0]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [16]:
arr1=np.array([1,2,3,4,5])
arr1=arr1.reshape(5,1)
print(arr1)

[[1]
 [2]
 [3]
 [4]
 [5]]


Print the shape of the above created array

In [17]:
print(arr1.shape)

(5, 1)


Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [25]:
arr2=np.arange(0,10)
print(arr2)
print(arr2[2])
print(arr2[3])
print(arr2[8])

[0 1 2 3 4 5 6 7 8 9]
2
3
8


Print alternate elements of that array

In [26]:
print(arr2[::2])

[0 2 4 6 8]


Change last 3 elements into 100 using broadcasting and print

In [27]:
arr2[-3:] = 100
print(arr2)

[  0   1   2   3   4   5   6 100 100 100]


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [29]:
matrix = np.random.randint(0,25,25).reshape(5,5)
print(matrix)
print(matrix[1:-1,1:-1])

[[21  1 22 18 23]
 [ 7  7  3  3  3]
 [13 22 11  2 16]
 [15  4  3  5  9]
 [23 23  1 13  2]]
[[ 7  3  3]
 [22 11  2]
 [ 4  3  5]]
